{% set version = "3.6.2" %}

package:
  name: singledispatch
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/singledispatch/singledispatch-{{ version }}.tar.gz
  sha256: d5bb9405a4b8de48e36709238e8b91b4f6f300f81a5132ba2531a9a738eca391

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - six

test:
  imports:
    - singledispatch

about:
  home: http://docs.python.org/3/library/functools.html#functools.singledispatch
  license: MIT
  license_file: LICENSE
  summary: This library brings functools.singledispatch from Python 3.4 to Python 2.6-3.3.

extra:
  recipe-maintainers:
    - jakirkham
