{% set version="3.4.0.3" %}

package:
  name: singledispatch
  version: {{ version }}

source:
  fn: singledispatch-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/singledispatch/singledispatch-{{ version }}.tar.gz
  md5: af2fc6a3d6cc5a02d0bf54d909785fcb

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - six

  run:
    - python
    - six

test:
  imports:
    - singledispatch

about:
  home: http://docs.python.org/3/library/functools.html#functools.singledispatch
  license: MIT
  summary: This library brings functools.singledispatch from Python 3.4 to Python 2.6-3.3.

extra:
  recipe-maintainers:
    - jakirkham
