{% set version = "3.5.0" %}

package:
  name: singledispatch
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/singledispatch/singledispatch-{{ version }}.tar.gz
  sha256: b5b6d32674e519b48a2186c0c1e68a751a9d789a30c34a9ba8cb04d9e505ea22

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - six

test:
  imports:
    - singledispatch

about:
  home: http://docs.python.org/3/library/functools.html#functools.singledispatch
  license: MIT
  license_file: LICENSE
  summary: This library brings functools.singledispatch from Python 3.4 to Python 2.6-3.3.

extra:
  recipe-maintainers:
    - jakirkham
